const GET_ENGAGEMENTS = 'GET_ENGAGEMENTS';
const GET_ENGAGEMENTS_SUCCESS = 'GET_ENGAGEMENTS_SUCCESS';
const GET_ENGAGEMENTS_FAILURE = 'GET_ENGAGEMENTS_FAILURE';

const GET_ENGAGEMENT = 'GET_ENGAGEMENT';
const GET_ENGAGEMENT_SUCCESS = 'GET_ENGAGEMENT_SUCCESS';
const GET_ENGAGEMENT_FAILURE = 'GET_ENGAGEMENT_FAILURE';

const GET_ENGAGEMENT_MESSAGES = 'GET_ENGAGEMENT_MESSAGES';
const GET_ENGAGEMENT_MESSAGES_SUCCESS = 'GET_ENGAGEMENT_MESSAGES_SUCCESS';
const GET_ENGAGEMENT_MESSAGES_FAILURE = 'GET_ENGAGEMENT_MESSAGES_FAILURE';

const CREATE_ENGAGEMENT_MESSAGE = 'CREATE_ENGAGEMENT_MESSAGE';
const CREATE_ENGAGEMENT_MESSAGE_SUCCESS = 'CREATE_ENGAGEMENT_MESSAGE_SUCCESS';
const CREATE_ENGAGEMENT_MESSAGE_FAILURE = 'CREATE_ENGAGEMENT_MESSAGE_FAILURE';

const GET_UNREAD_COUNT = 'GET_UNREAD_COUNT';
const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS';
const MARK_MESSAGES_READ_SUCCESS = 'MARK_MESSAGES_READ_SUCCESS';

export default {
    GET_ENGAGEMENTS,
    GET_ENGAGEMENTS_SUCCESS,
    GET_ENGAGEMENTS_FAILURE,
    GET_ENGAGEMENT,
    GET_ENGAGEMENT_SUCCESS,
    GET_ENGAGEMENT_FAILURE,
    GET_ENGAGEMENT_MESSAGES,
    GET_ENGAGEMENT_MESSAGES_SUCCESS,
    GET_ENGAGEMENT_MESSAGES_FAILURE,
    CREATE_ENGAGEMENT_MESSAGE,
    CREATE_ENGAGEMENT_MESSAGE_SUCCESS,
    CREATE_ENGAGEMENT_MESSAGE_FAILURE,
    GET_UNREAD_COUNT,
    GET_UNREAD_COUNT_SUCCESS,
    MARK_MESSAGES_READ_SUCCESS
};