const GET_USERS = 'GET_USERS';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

const GET_LATEST_USERS = 'GET_LATEST_USERS';
const GET_LATEST_USERS_SUCCESS = 'GET_LATEST_USERS_SUCCESS';
const GET_LATEST_USERS_FAILURE = 'GET_LATEST_USERS_FAILURE';

const GET_USER = 'GET_USER';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FAILURE = 'GET_USER_FAILURE';

const GET_USER_LISTINGS = 'GET_USER_LISTINGS';
const GET_USER_LISTINGS_SUCCESS = 'GET_USER_LISTINGS_SUCCESS';
const GET_USER_LISTINGS_FAILURE = 'GET_USER_LISTINGS_FAILURE';

export default {
    GET_USERS,
    GET_USERS_SUCCESS,
    GET_USERS_FAILURE,
    GET_LATEST_USERS,
    GET_LATEST_USERS_SUCCESS,
    GET_LATEST_USERS_FAILURE,
    GET_USER,
    GET_USER_SUCCESS,
    GET_USER_FAILURE,
    GET_USER_LISTINGS,
    GET_USER_LISTINGS_SUCCESS,
    GET_USER_LISTINGS_FAILURE
};