const GET_USERS = 'GET_USERS';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export default {
    GET_USERS,
    GET_USERS_SUCCESS,
    GET_USERS_FAILURE
};