
const DELETE_IMAGE = 'DELETE_IMAGE';
const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE';

export default {
    DELETE_IMAGE,
    DELETE_IMAGE_SUCCESS,
    DELETE_IMAGE_FAILURE
};