const AUTHENTICATE = 'AUTHENTICATE';
const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
const USER_LOGOUT = 'USER_LOGOUT';

const VERIFY_TOKEN = 'VERIFY_TOKEN';
const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
const VERIFY_TOKEN_FAILURE = 'VERIFY_TOKEN_FAILURE';

const REGISTER = 'REGISTER';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

const GET_ACCOUNT = 'GET_ACCOUNT';
const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';

const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
const UPDATE_ADDRESS_FAILURE = 'UPDATE_ADDRESS_FAILURE';

export default {
    AUTHENTICATE,
    AUTHENTICATE_SUCCESS,
    AUTHENTICATE_FAILURE,
    USER_LOGOUT,
    VERIFY_TOKEN_SUCCESS,
    VERIFY_TOKEN_FAILURE,
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    GET_ACCOUNT,
    GET_ACCOUNT_SUCCESS,
    UPDATE_ADDRESS,
    UPDATE_ADDRESS_SUCCESS,
    UPDATE_ADDRESS_FAILURE
};